/**
 * The level audit (docs/level-audit.md) from docs/level-curve.json: per-tier
 * curve summary before and after the Director, the sawtooth check, outliers,
 * and neighbours that came out too alike. Pure function of the curve file.
 */

export interface Measured {
  d: number;
  opening: number;
  avgMoves: number;
  minMoves: number;
  twoBend: number;
  decoys: number;
  deadEnd: number;
  humanTime: number;
  fun: number;
  /** fun shape detail (bank builds from the curve-and-fun milestone on) */
  easyOpen?: number;
  firstSeconds?: number;
  crunch?: number;
  finale?: number;
}

export interface CurveLevel {
  n: number;
  ch: number;
  slot: number;
  role: string;
  shape: string;
  mech: string;
  goal: string;
  base: number;
  /** designed target per tier */
  target: number[];
  /** measured d of the bank's board per tier (after) */
  after: number[];
  /** the knobs of each tier's board, short form */
  knobs?: string[];
  /** tier-2 metrics */
  t2: Measured | null;
  /** per tier, the fun marks passed as three 0/1 characters: foothold, crunch, finale */
  fun?: string[];
  /** feature distance to the previous level's tier-2 board (small = alike) */
  sim: number;
  /** the pre-Director journeyLevel board, measured the same way */
  before: (Measured & { solved: boolean; shape: string; wind: string }) | null;
}

export interface CurveFile {
  version: number;
  K: number;
  levels: CurveLevel[];
  build?: { seconds: number; workers: number; tried: number; rejected: Record<string, number>; repaired: number; failed: number[]; bankBytes: number };
}

const mean = (a: number[]) => (a.length ? a.reduce((s, x) => s + x, 0) / a.length : NaN);
const f2 = (x: number) => (Number.isFinite(x) ? x.toFixed(2) : '–');
const ROLES = ['open', 'focus', 'plain', 'focus', 'focus', 'mix', 'rest', 'focus', 'mix', 'focus', 'peak', 'festival'];
/** Too alike: tier-2 feature distance to the previous level under this. */
export const SIMILAR = 0.12;

export function renderAudit(c: CurveFile): string {
  const L = c.levels.filter((l) => l.after && l.after.length === 5);
  const out: string[] = [];
  const b = c.build;
  out.push('# Level audit: the Flower Road, levels 1–600 × 5 tiers');
  out.push('');
  out.push('Generated by `npm run bank` (scripts/build-bank.ts) from the bank it just built; `npm run bank:audit` re-renders it from `docs/level-curve.json`.');
  out.push('d is the measured difficulty (0–1) from the bot personas (src/director/metrics.ts). "Before" is the pre-Director `journeyLevel` board for the same level, measured with the same metrics.');
  out.push('');
  if (b) {
    const rej = Object.entries(b.rejected).sort((x, y) => y[1] - x[1]).map(([k, v]) => `${k} ${v}`).join(', ');
    out.push(`**Build:** K = ${c.K} candidates per tier, ${b.workers} threads, ${b.seconds} s; ${b.tried} boards built; rejected by the validators: ${rej || 'none'}; ${b.repaired} levels needed a monotonicity repair; failed levels: ${b.failed.length ? b.failed.join(', ') : 'none'}. Bank size ${(b.bankBytes / 1024).toFixed(1)} KB.`);
    out.push('');
  }

  // 1. Before vs after, per 50-level band.
  out.push('## Curve summary (mean d)');
  out.push('');
  out.push('| Levels | Before | Tier 0 | Tier 1 | Tier 2 | Tier 3 | Tier 4 | Designed base |');
  out.push('|---|---|---|---|---|---|---|---|');
  for (let a = 1; a <= 600; a += 50) {
    const band = L.filter((l) => l.n >= a && l.n < a + 50);
    if (!band.length) continue;
    const before = band.filter((l) => l.before).map((l) => l.before!.d);
    out.push(`| ${a}–${a + 49} | ${f2(mean(before))} | ${[0, 1, 2, 3, 4].map((t) => f2(mean(band.map((l) => l.after[t])))).join(' | ')} | ${f2(mean(band.map((l) => l.base)))} |`);
  }
  const allBefore = L.filter((l) => l.before).map((l) => l.before!.d);
  out.push(`| **all** | **${f2(mean(allBefore))}** | ${[0, 1, 2, 3, 4].map((t) => `**${f2(mean(L.map((l) => l.after[t])))}**`).join(' | ')} | **${f2(mean(L.map((l) => l.base)))}** |`);
  out.push('');
  const last = (k: number) => L.filter((l) => l.ch >= 50 - k);
  const first = (k: number) => L.filter((l) => l.ch < k && l.n > 6);
  out.push(`Rise across the road (tier 2): first five places ${f2(mean(first(5).map((l) => l.after[2])))} → last five places ${f2(mean(last(5).map((l) => l.after[2])))}; before: ${f2(mean(first(5).filter((l) => l.before).map((l) => l.before!.d)))} → ${f2(mean(last(5).filter((l) => l.before).map((l) => l.before!.d)))}.`);
  out.push('');
  out.push(`Per tier, first five places → last five: ${[0, 1, 2, 3, 4].map((t) => `tier ${t} ${f2(mean(first(5).map((l) => l.after[t])))} → ${f2(mean(last(5).map((l) => l.after[t])))}`).join('; ')}.`);
  const unsolvedBefore = L.filter((l) => l.before && !l.before.solved).map((l) => l.n);
  out.push('');
  out.push(`Before the Director, ${unsolvedBefore.length} Journey boards had no clear without a reshuffle (the solver found none): ${unsolvedBefore.slice(0, 40).join(', ')}${unsolvedBefore.length > 40 ? ', …' : ''}. Every bank board is solver-proven.`);
  out.push('');

  // 2. Monotone in tier.
  const mono = L.filter((l) => l.after.every((d, t) => t === 0 || d >= l.after[t - 1])).length;
  const strict = L.filter((l) => l.after.every((d, t) => t === 0 || d > l.after[t - 1])).length;
  out.push('## Tiers');
  out.push('');
  out.push(`d never falls as the tier rises on ${mono} of ${L.length} levels (${((100 * mono) / Math.max(1, L.length)).toFixed(1)} %); strictly rising on ${strict}. The spread between tier 0 and tier 4 averages ${f2(mean(L.map((l) => l.after[4] - l.after[0])))}.`);
  out.push('');

  // 3. Sawtooth.
  out.push('## Sawtooth inside chapters');
  out.push('');
  out.push('Mean d by slot (all chapters after the first):');
  out.push('');
  out.push(`| Slot | ${ROLES.map((r, i) => `${i + 1} ${r}`).join(' | ')} |`);
  out.push(`|---|${ROLES.map(() => '---').join('|')}|`);
  const later = L.filter((l) => l.ch > 0);
  for (const t of [0, 2, 4]) out.push(`| Tier ${t} | ${ROLES.map((_, s) => f2(mean(later.filter((l) => l.slot === s).map((l) => l.after[t])))).join(' | ')} |`);
  out.push(`| Before | ${ROLES.map((_, s) => f2(mean(later.filter((l) => l.slot === s && l.before).map((l) => l.before!.d)))).join(' | ')} |`);
  out.push(`| Designed | ${ROLES.map((_, s) => f2(mean(later.filter((l) => l.slot === s).map((l) => l.base)))).join(' | ')} |`);
  out.push('');
  let saw = 0;
  let chapters = 0;
  const flat: number[] = [];
  for (let ch = 1; ch < 50; ch++) {
    const c2 = L.filter((l) => l.ch === ch);
    if (c2.length !== 12) continue;
    chapters++;
    const d = c2.map((l) => l.after[2]);
    const sorted = d.slice().sort((x, y) => x - y);
    const rest = d[6];
    const open = d[0];
    const peak = d[10];
    const ok = rest <= sorted[3] && open <= sorted[5] && peak >= sorted[8];
    if (ok) saw++;
    else flat.push(ch + 1);
  }
  out.push(`Sawtooth check (tier 2: the rest board among the four easiest of its chapter, the open board in the easier half, the peak among the four hardest): **${saw} of ${chapters} chapters** pass.${flat.length ? ` Chapters that don't: ${flat.join(', ')}.` : ''}`);
  out.push('');
  // The stricter shape: the peak is the chapter's single hardest board, the festival
  // sits below it, and the open and rest boards are both among the four easiest.
  let strictSaw = 0;
  let peakTop = 0;
  let festBelow = 0;
  for (let ch = 1; ch < 50; ch++) {
    const c2 = L.filter((l) => l.ch === ch);
    if (c2.length !== 12) continue;
    const d = c2.map((l) => l.after[2]);
    const sorted = d.slice().sort((x, y) => x - y);
    const top = d[10] >= Math.max(...d);
    const fest = d[11] < d[10];
    if (top) peakTop++;
    if (fest) festBelow++;
    if (top && fest && d[6] <= sorted[3] && d[0] <= sorted[3]) strictSaw++;
  }
  out.push(`Strict sawtooth (tier 2): the peak is the chapter's hardest board in **${peakTop} of ${chapters}**, the festival sits below the peak in **${festBelow}**, and all of that with the open and rest boards among the four easiest in **${strictSaw}**.`);
  out.push('');

  // 4. Outliers.
  const outliers: string[] = [];
  for (const l of L) {
    for (let t = 0; t < 5; t++) {
      const gap = l.after[t] - l.target[t];
      if (Math.abs(gap) > 0.2) outliers.push(`| ${l.n} | ${t} | ${l.role} | ${l.shape} | ${l.mech || '–'} | ${f2(l.after[t])} | ${f2(l.target[t])} | ${gap > 0 ? '+' : ''}${gap.toFixed(2)} |`);
    }
  }
  out.push('## Outliers');
  out.push('');
  out.push(`${outliers.length} level-tiers miss their designed target by more than 0.2 (the identity's shape and mechanics bound how easy or hard its board can be; the search takes the closest valid board).`);
  if (outliers.length) {
    out.push('');
    out.push('| Level | Tier | Role | Shape | Mechanics | d | Target | Gap |');
    out.push('|---|---|---|---|---|---|---|---|');
    out.push(...outliers.slice(0, 40));
    if (outliers.length > 40) out.push(`| … | | | | | | | ${outliers.length - 40} more |`);
  }
  out.push('');

  // 5. Fun: the marks every board is checked for (src/director/metrics.ts, FUN).
  const funned = L.filter((l) => l.fun && l.fun.length === 5);
  if (funned.length) {
    const rate = (k: number, tiers = [0, 1, 2, 3, 4]) => {
      let pass = 0;
      let all = 0;
      for (const l of funned) for (const t of tiers) {
        all++;
        if (l.fun![t][k] === '1') pass++;
      }
      return `${((100 * pass) / Math.max(1, all)).toFixed(1)} %`;
    };
    const varied = L.filter((l) => l.n > 6);
    out.push('## Fun');
    out.push('');
    out.push(`Share of the ${funned.length * 5} bank boards that pass each mark (tier 4 alone in brackets):`);
    out.push('');
    out.push(`- **Early foothold** (an easy 0–1 bend pair at the start, found by the human-like scanner inside 10 s): ${rate(0)} (${rate(0, [4])})`);
    out.push(`- **Mid-board crunch** (legal pairs in the middle third fall at least 40 % below the opening): ${rate(1)} (${rate(1, [4])})`);
    out.push(`- **Combo finish** (the last third connects almost everything left): ${rate(2)} (${rate(2, [4])})`);
    out.push(`- **Variety** (tier-2 board at least ${SIMILAR} from the previous level's in feature space): ${((100 * varied.filter((l) => l.sim >= SIMILAR).length) / Math.max(1, varied.length)).toFixed(1)} %`);
    out.push('');
  }

  // 6. Too similar to neighbours.
  const alike = L.filter((l) => l.n > 6 && l.sim < SIMILAR);
  out.push('## Too similar to neighbours');
  out.push('');
  out.push(`Tier-2 boards whose feature vector (shape, mechanics, goal, stone layout and count, months, d) sits within ${SIMILAR} of the previous level's: **${alike.length}**.`);
  if (alike.length) {
    out.push('');
    out.push('| Level | Previous | Shape | Mechanics | Distance |');
    out.push('|---|---|---|---|---|');
    for (const l of alike.slice(0, 40)) out.push(`| ${l.n} | ${l.n - 1} | ${l.shape} | ${l.mech || '–'} | ${l.sim.toFixed(3)} |`);
  }
  out.push('');

  // 7. Per-chapter table.
  out.push('## Per place (mean d of the 12 levels)');
  out.push('');
  out.push('| Place | Before | T0 | T2 | T4 | Base |');
  out.push('|---|---|---|---|---|---|');
  for (let ch = 0; ch < 50; ch++) {
    const c2 = L.filter((l) => l.ch === ch);
    if (!c2.length) continue;
    out.push(`| ${ch + 1} | ${f2(mean(c2.filter((l) => l.before).map((l) => l.before!.d)))} | ${f2(mean(c2.map((l) => l.after[0])))} | ${f2(mean(c2.map((l) => l.after[2])))} | ${f2(mean(c2.map((l) => l.after[4])))} | ${f2(mean(c2.map((l) => l.base)))} |`);
  }
  out.push('');
  return out.join('\n');
}
