#!/usr/bin/env node
/**
 * Bundle only the font slices the app actually uses.
 *
 * Fontsource splits CJK fonts into ~100 unicode-range slices (50 MB+ in total).
 * This script scans the source for every character we render, keeps just the
 * slices that cover them, copies those .woff2 files into src/styles/fonts/ and
 * writes src/styles/fonts.css. Re-run after adding new Korean/Japanese text:
 *
 *   npm run fonts
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, copyFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'src/styles/fonts');

const FONTS = [
  { pkg: 'gowun-batang', weights: [400, 700] },
  { pkg: 'gowun-dodum', weights: [400] },
  { pkg: 'zen-old-mincho', weights: [500, 600] },
];

// 1. Characters used anywhere in the app.
const chars = new Set();
for (let c = 0x20; c <= 0x7e; c++) chars.add(c);
for (const extra of '·×—–’‘“”…★☆•→←✓') chars.add(extra.codePointAt(0));
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      if (name !== 'fonts') walk(p);
    } else if (/\.(ts|html|css)$/.test(name)) {
      for (const ch of readFileSync(p, 'utf8')) chars.add(ch.codePointAt(0));
    }
  }
};
walk(join(root, 'src'));
for (const ch of readFileSync(join(root, 'index.html'), 'utf8')) chars.add(ch.codePointAt(0));

// 2. Keep only @font-face blocks whose unicode-range intersects our characters.
const parseRanges = (s) =>
  s.split(',').map((part) => {
    const [a, b] = part.trim().replace(/^U\+/i, '').split('-');
    const lo = parseInt(a, 16);
    return [lo, b ? parseInt(b, 16) : lo];
  });
const covers = (ranges) => [...chars].some((c) => ranges.some(([lo, hi]) => c >= lo && c <= hi));

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
let css = '/* Generated by scripts/subset-fonts.mjs — do not edit. SIL Open Font License 1.1. */\n';
let bytes = 0;
let files = 0;
for (const { pkg, weights } of FONTS) {
  const pkgDir = join(root, 'node_modules/@fontsource', pkg);
  for (const w of weights) {
    const src = readFileSync(join(pkgDir, `${w}.css`), 'utf8');
    for (const block of src.match(/@font-face\s*{[^}]+}/g) ?? []) {
      const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
      if (range && !covers(parseRanges(range))) continue;
      const file = /url\(\.\/files\/([^)]+\.woff2)\)/.exec(block)?.[1];
      if (!file) continue;
      copyFileSync(join(pkgDir, 'files', file), join(outDir, file));
      bytes += statSync(join(outDir, file)).size;
      files++;
      css += block
        .replace(/src:[^;]+;/, `src: url(./fonts/${file}) format('woff2');`)
        .replace('font-display: swap', 'font-display: block') + '\n';
    }
  }
}
writeFileSync(join(root, 'src/styles/fonts.css'), css);
console.log(`fonts: ${files} slices, ${(bytes / 1024).toFixed(0)} KB, ${chars.size} distinct characters`);
